### ISSUE TITLE
Adding new gateway

### ISSUE THREAD

**Issue by theRealRizeo** [Payum/PayumServerUI#3]
![error](https://cloud.githubusercontent.com/assets/121492/11423006/c95f0988-9451-11e5-8298-63ecf979b9c3.PNG)
I'm getting an error of 404 when trying to add a new gateway via the client UI. The server is running and configured on the Settings of the Client

**Comment by makasim** [comment]
Are you getting it in the UI? Try to remove the last slash in the url "/". Go to settings and correct server url there.

**Comment by theRealRizeo** [comment]
Okay, I noticed that in the client it references the JavaScript payum.js in the header but its not in the client, so had to copy from the server. Now when I try and save a Gateway, I get an error on the UI "Invalid Form", but if I refresh the Gateways, I can see its added

**Comment by makasim** [comment]
How do you run server? with docker?

**Comment by theRealRizeo** [comment]
No, I cant install Docker on Windows 10 Home edition. I used composer to install the dependencies and executed ` php -S 127.0.0.1:8000 web/index.php `

**Comment by makasim** [comment]
Unfortunately Php server is not enough, (because of payum.js). It is simple php app. try to run it with apache server or something like that. Would be good to add env var PAYUM_DEBUG=1 to see more details on errors.

This setup has to work. This way it works on server.payum.org. (without docker).
